name: Windows Build

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.4.3
  ARTIFACT:     qt-inane-build.zip

jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
      
      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qtcore qtgui qtwidgets qtsql
          setup-python: false
          
      - name: (5) Download JOM
        uses: suisei-cn/actions-download-file@v1
        with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

      - name: (6) Unzip JOM
        working-directory: ${{ runner.temp }}
        run:  |
              7z x jom.zip -ojom
      
      - name: Make NCL build dir
        run: mkdir ${{github.workspace}}\external\ncl\build
        
      - name: (4) Install NCL
        working-directory: ${{github.workspace}}\external\ncl\build
        run: | 
             cmake ..
             cmake --build . --config Release -- -j 4
              
      - name: (7) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (8) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: (9) Build
        working-directory: ${{ runner.temp }}\build
        run:  |
              qmake -r ${{ env.SOURCE_DIR }}\INANE.pro
              ${{ runner.temp }}\jom\jom -j2
              cd release
              windeployqt --qmldir ${{ env.SOURCE_DIR }} INANE.exe --pdb --release --compiler-runtime
              copy C:\Windows\System32\concrt140.dll . 
              copy C:\Windows\System32\vccorlib140.dll .
              copy C:\Windows\System32\msvcp140.dll .
              copy C:\Windows\System32\vcruntime140.dll .
              
      - name: (10) Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a qt-inane-build.zip ${{ runner.temp }}\build\* -r
              
      - name: (11) Save build artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
